# Generated by Django 5.0.2 on 2024-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100, null=True)),
                ('Material', models.CharField(max_length=100, null=True)),
                ('Cost', models.IntegerField(null=True)),
                ('Design', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
